
[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
# Aktivér kernekontroller + import-sortering (I)
select = ["E", "F", "I", "B", "UP"]
ignore = []
fix = true

[tool.ruff.lint.isort]
known-first-party = ["agent", "app"]
combine-as-imports = true

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
disallow_untyped_defs = false
warn_unused_ignores = true
warn_redundant_casts = true
show_error_codes = true
pretty = true
